config/routes.rb
Rails.application.routes.draw do
 
  root 'home#index'
  resources :addresses
  get 'dashboard' => 'dashboard#index'
  resources :abouts
  devise_for :users

end

app/models/about.rb
# == Schema Information
#
# Table name: abouts
#
#  id                    :integer          not null, primary key
#  aboutinfo             :text(65535)
#  shopname              :string(255)
#  created_at            :datetime         not null
#  updated_at            :datetime         not null
#  user_id               :integer
#  shopimg_file_name     :string(255)
#  shopimg_content_type  :string(255)
#  shopimg_file_size     :integer
#  shopimg_updated_at    :datetime
#  shopimg1_file_name    :string(255)
#  shopimg1_content_type :string(255)
#  shopimg1_file_size    :integer
#  shopimg1_updated_at   :datetime
#  shopimg2_file_name    :string(255)
#  shopimg2_content_type :string(255)
#  shopimg2_file_size    :integer
#  shopimg2_updated_at   :datetime
#  shopimg3_file_name    :string(255)
#  shopimg3_content_type :string(255)
#  shopimg3_file_size    :integer
#  shopimg3_updated_at   :datetime
#

class About < ActiveRecord::Base

	belongs_to :user


	has_attached_file :shopimg, styles: { large: "600x600",  medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	has_attached_file :shopimg1, styles: { large: "600x600",  medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	has_attached_file :shopimg2, styles: { large: "600x600",  medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	has_attached_file :shopimg3, styles: { large: "600x600",  medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"	
    validates_attachment_content_type :shopimg, content_type: /\Aimage\/.*\z/
    validates_attachment_content_type :shopimg1, content_type: /\Aimage\/.*\z/
    validates_attachment_content_type :shopimg2, content_type: /\Aimage\/.*\z/
    validates_attachment_content_type :shopimg3, content_type: /\Aimage\/.*\z/
end

app/models/address.rb
class Address < ActiveRecord::Base

	belongs_to :user
	
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :about       
  has_many :address
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_about, only: [:show, :edit, :update, :destroy]

  # GET /abouts
  # GET /abouts.json
  def index
    @abouts =  current_user.about
    if About.where(:user_id => current_user.id).present?
         abouts_path
     else
          redirect_to new_about_path
    end    
  end

  # GET /abouts/1
  # GET /abouts/1.json
  def show
  end

  # GET /abouts/new
  def new
    @about =  About.new
  end

  # GET /abouts/1/edit
  def edit
  end

  # POST /abouts
  # POST /abouts.json
  def create
    @about = About.new(about_params)
    @about.user_id = current_user.id
    respond_to do |format|
      if @about.save
        format.html { redirect_to @about, notice: 'About was successfully created.' }
        format.json { render :show, status: :created, location: @about }
      else
        format.html { render :new }
        format.json { render json: @about.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /abouts/1
  # PATCH/PUT /abouts/1.json
  def update
    respond_to do |format|
      if @about.update(about_params)
        format.html { redirect_to @about, notice: 'About was successfully updated.' }
        format.json { render :show, status: :ok, location: @about }
      else
        format.html { render :edit }
        format.json { render json: @about.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /abouts/1
  # DELETE /abouts/1.json
  def destroy
    @about.destroy
    respond_to do |format|
      format.html { redirect_to abouts_url, notice: 'About was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_about
      @about = About.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def about_params
      params.require(:about).permit(:aboutinfo, :shopname, :shopimg,:shopimg1, :shopimg2, :shopimg3, :user_id)
    end
end
  

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_address, only: [:show, :edit, :update, :destroy]

  # GET /addresses
  # GET /addresses.json
  def index
    @addresses = current_user.address
    if Address.where(:user_id => current_user.id).present?
        addresses_path
    else
      redirect_to new_address_path
    end
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
  end

  # GET /addresses/new
  def new
    @address = Address.new
  end

  # GET /addresses/1/edit
  def edit
  end

  # POST /addresses
  # POST /addresses.json
  def create
    @address = Address.new(address_params)
    @address.user_id = current_user.id
    respond_to do |format|
      if @address.save
        format.html { redirect_to @address, notice: 'Address was successfully created.' }
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1
  # PATCH/PUT /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to @address, notice: 'Address was successfully updated.' }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address.destroy
    respond_to do |format|
      format.html { redirect_to addresses_url, notice: 'Address was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def address_params
      params.require(:address).permit(:name, :address, :city, :state, :zipcode, :mobileno, :landlineno, :emailid, :website, :user_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	  before_action :authenticate_user!
	 before_action :set_address, only: [:show, :edit, :update, :destroy]
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/abouts/_form.html.erb
<%= form_for @about,  html: { multipart: true } do |f| %>
  <% if @about.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@about.errors.count, "error") %> prohibited this about from being saved:</h2>

      <ul>
      <% @about.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group col-sm-12">
    <label  class="col-sm-2 control-label">Shop Name :</label>
    <div class="col-sm-7">
    <%= f.text_field :shopname, class: "form-control"%>
    <br>
    </div>
  </div>
  <div class="form-group col-sm-12">
    <label  class="col-sm-2 control-label">About Info :</label>
    <div class="col-sm-7">
    <%= f.text_area :aboutinfo, class: "form-control", rows: 5 %>
    <br>
    </div>
  </div>
  <div class="form-group col-sm-12">
    <label  class="col-sm-2 control-label">Upload You shop Image (Only 4 Image) :</label>
    <div class="col-sm-7">
    <%= f.file_field :shopimg %>
    <%= f.file_field :shopimg1 %>
    <%= f.file_field :shopimg2 %>
    <%= f.file_field :shopimg3 %>
    <br>
    </div>
  </div>



   <div class="form-group">
   <div class="col-sm-6 pull-right">
        <%= link_to 'Back', abouts_path, class: "btn btn-primary btn-sm" %>
        <%= f.submit class: "btn btn-primary btn-sm" %>
    </div>
  </div>
<% end %>

app/views/abouts/edit.html.erb
 <h1 style="color:OrangeRed"><center>Editing About</center></h1><hr>

<%= render 'form' %>

<!-- <%= link_to 'Show', @about %> |
<%= link_to 'Back', abouts_path %>  -->

app/views/abouts/index.html.erb
<p id="notice"><%= notice %></p>

<!-- <h1>Listing Abouts</h1> -->
<% @abouts.each do |about| %>
<div class="row">
  <div class="col-md-12">
    <div class="col-md-4">
      <div class="list-group">
        <a href="#" class="list-group-item active">
          List 
        </a>
        <a href="#" class="list-group-item">Dapibus ac facilisis in
        </a>
        <a href="#" class="list-group-item">Morbi leo risus
        </a>
      </div>
    </div>

    <div class="col-md-8">
            <div class="col-md-8">
                <div class="panel panel-primary">
                  <div class="panel-heading">
                    <h3 class="panel-title">Shop Name :</h3>
                  </div>
                  <div class="panel-body">
                    <p><%= about.shopname %></p>
                  </div>
                </div>
             </div>
             <div class="col-md-12">
                <div class="panel panel-primary">
                  <div class="panel-heading">
                    <h3 class="panel-title">About Information :</h3>
                  </div>
                  <div class="panel-body">
                     <p>&nbsp;&nbsp;&nbsp;&nbsp; <%= about.aboutinfo %></p>
                  </div>
                </div>
              </div>
              <div class="col-md-12">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                      <h3 class="panel-title">Shop Images :</h3>
                    </div>
                    <div class="panel-body">
                       <div class="col-md-3"><%= image_tag about.shopimg.url(:thumb) %></div>
                       <div class="col-md-3"> <%= image_tag about.shopimg1.url(:thumb) %></div>
                       <div class="col-md-3"> <%= image_tag about.shopimg2.url(:thumb) %></div>
                       <div class="col-md-3"><%= image_tag about.shopimg3.url(:thumb) %></div>
                    </div>
                </div>
              </div>
              <div class="form-group col-md-12 col-md-offset-4">
                <%= link_to 'Destroy', about, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary btn-sm " %>
                <%= link_to ' Edit ', edit_about_path(about), class: "btn btn-primary btn-sm" %>
              </div>
    </div>
   </div>
</div>

     
    <% end %>
  

<br>

<!-- <%= link_to 'New About', new_about_path %> -->

app/views/abouts/new.html.erb
<h1>New About</h1>

<%= render 'form' %>

<%= link_to 'Back', abouts_path %>

app/views/abouts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Aboutinfo:</strong>
  <%= @about.aboutinfo %>
</p>

<%= link_to 'Edit', edit_about_path(@about) %> |
<%= link_to 'Back', abouts_path %>

app/views/addresses/_form.html.erb
<%= form_for(@address) do |f| %>
  <% if @address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
      <% @address.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group col-sm-12">
    <label  class="col-sm-2 control-label">Name :</label>
    <div class="col-sm-7">
    <%= f.text_field :name, class: "form-control"%>
    <br>
    </div>
  </div>
  <div class="form-group col-sm-12">
    <label  class="col-sm-2 control-label">Address Info :</label>
    <div class="col-sm-7">
    <%= f.text_area :address, class: "form-control", rows: 3 %>
    <br>
    </div>
  </div>
   <div class="form-group col-sm-12">
    <label  class="col-sm-2 control-label">City :</label>
    <div class="col-sm-7">
    <%= f.text_field :city, class: "form-control"%>
    <br>
    </div>
  </div> <div class="form-group col-sm-12">
    <label  class="col-sm-2 control-label">State :</label>
    <div class="col-sm-7">
    <%= f.text_field :state, class: "form-control"%>
    <br>
    </div>
  </div> <div class="form-group col-sm-12">
    <label  class="col-sm-2 control-label">Zip Code :</label>
    <div class="col-sm-7">
    <%= f.text_field :zipcode, class: "form-control"%>
    <br>
    </div>
  </div> <div class="form-group col-sm-12">
    <label  class="col-sm-2 control-label">Mobile No :</label>
    <div class="col-sm-7">
    <%= f.text_field :mobileno, class: "form-control"%>
    <br>
    </div>
  </div> <div class="form-group col-sm-12">
    <label  class="col-sm-2 control-label">Landline No :</label>
    <div class="col-sm-7">
    <%= f.text_field :landlineno, class: "form-control"%>
    <br>
    </div>
  </div> <div class="form-group col-sm-12">
    <label  class="col-sm-2 control-label">Email Id :</label>
    <div class="col-sm-7">
    <%= f.text_field :emailid, class: "form-control"%>
    <br>
    </div>
  </div> <div class="form-group col-sm-12">
    <label  class="col-sm-2 control-label">Website Url :</label>
    <div class="col-sm-7">
    <%= f.text_field :website, class: "form-control"%>
    <br>
    </div>
  </div>



   <div class="form-group">
   <div class="col-sm-6 pull-right">
         <%= f.submit class: "btn btn-primary btn-sm" %>
    </div>
  </div>
<% end %>

app/views/addresses/edit.html.erb
<h1>Editing Address</h1>

<%= render 'form' %>

<%= link_to 'Show', @address %> |
<%= link_to 'Back', addresses_path %>

app/views/addresses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Addresses</h1>


<% @addresses.each do |address| %>
  <div class="row">
  <div class="col-md-12">
    <div class="col-md-4">
      <div class="list-group">
        <a href="#" class="list-group-item active">
          List 
        </a>
        <a href="#" class="list-group-item">Dapibus ac facilisis in
        </a>
        <a href="#" class="list-group-item">Morbi leo risus
        </a>
      </div>
    </div>

    <div class="col-md-8">
             <div class="col-md-12">
                <div class="panel panel-primary">
                  <div class="panel-heading">
                    <h3 class="panel-title">Adderss Information :</h3>
                  </div>
                  <div class="panel-body">
                  <div class="col-md-4">
                    <span> Name: </span>      <%= address.name %> </br>
                  </div>  
                  <div class="col-md-12"> 
                    <span> Address: </span>   <%= address.address %>
                  </div>
                  <div class="col-md-4"> 
                    <span> City: </span>      <%= address.city %>
                  </div>
                  <div class="col-md-4">
                    <span> State: </span>     <%= address.state %>
                  </div>
                  <div class="col-md-4">  
                    <span> Zip code: </span>   <%= address.zipcode %> 
                  </div>
                  <div class="col-md-4">
                    <span> Mobile No: </span>  <%= address.mobileno %> 
                  </div>
                  <div class="col-md-8">
                    <span> Landlineno: </span><%= address.landlineno %> 
                  </div> 
                  <div class="col-md-5">
                    <span> Email Id: </span>   <%= address.emailid %> 
                  </div>
                  <div class="col-md-4">
                    <span> Website: </span>   <%= address.website %>
                  </div>
                </div>
              </div>
              <div class="col-md-12">
                <div class="panel panel-primary">
                  <div class="panel-heading">
                    <h3 class="panel-title">Map :</h3>
                  </div>
                  <div class="panel-body">
                      <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3780.571018233566!2d73.79184411446018!3d18.638355087340532!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bc2b9b54638255d%3A0x4c82ff49c89ae675!2sKasturi+Infotec!5e0!3m2!1sen!2sin!4v1478589139384" width="630" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
                  </div>
                </div>
              </div>
          



              <div class="form-group col-md-12 col-md-offset-4">

      <!--         <%= link_to 'Show', address, class:"btn btn-primary btn-sm" %> -->
              <%= link_to 'Edit', edit_address_path(address), class:"btn btn-primary btn-sm" %>
              <%= link_to 'Destroy', address, method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-primary btn-sm" %>
             
              </div>
    </div>
   </div>
</div>



    
    
    <% end %>


 <!--    <%= link_to 'New Address', new_address_path %>
 -->

app/views/addresses/new.html.erb
<h1>New Address</h1>

<%= render 'form' %>

<%= link_to 'Back', addresses_path %>

app/views/addresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @address.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @address.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @address.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @address.state %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @address.zipcode %>
</p>

<p>
  <strong>Mobileno:</strong>
  <%= @address.mobileno %>
</p>

<p>
  <strong>Landlineno:</strong>
  <%= @address.landlineno %>
</p>

<p>
  <strong>Emailid:</strong>
  <%= @address.emailid %>
</p>

<p>
  <strong>Website:</strong>
  <%= @address.website %>
</p>

<%= link_to 'Edit', edit_address_path(@address) %> |
<%= link_to 'Back', addresses_path %>

app/views/dashboard/index.html.erb
   
            <div class="list-group">
                <a href="/abouts" class="list-group-item visitor" style="background-color: #15a589;">
                    <h3 class="pull-right"> 
                    <i class="fa fa-user"></i>
                    </h3>
                    <h4 class="list-group-item-heading">
                        About</h4>
                    <p class="list-group-item-text">
                         Add You Info</p>
                </a><a href="/addresses" class="list-group-item visitor" style="background-color: #18bc9c;">
                    <h3 class="pull-right">
                         <i class="fa fa-comments-o"></i>
                    </h3>
                    <h4 class="list-group-item-heading">
                        Address</h4>
                    <p class="list-group-item-text">
                        Add Your Shop/Institude/Mall...etc Address</p>
                </a>
            </div>    
            <div class="list-group">

                <a href="https://login.secureserver.net/" class="list-group-item visitor" style="background-color: #15a589;">
                    <h3 class="pull-right">
                         <i class="fa fa-envelope-o"></i>
                    </h3>
                    <h4 class="list-group-item-heading ">                    
                        Add unic product for sales..</h4>
                    <p class="list-group-item-text">
                        unic product</p>
                </a>
                <a href="/user/me/settings" class="list-group-item visitor" style="background-color: #18bc9c;">
                        <h3 class="pull-right">
                            <i class="fa fa-bullhorn"></i>
                        </h3>
                        <h4 class="list-group-item-heading">
                            Notifications Settings</h4>
                        <p class="list-group-item-text">
                            Take Control.</p>
                    </a>
             </div>
                    
                
             <div class="list-group">
    
                       <a href="/filedepot" class="list-group-item visitor" style="background-color: #15a589;">
                    <h3 class="pull-right">
                        <i class="fa fa-file-text-o"></i>
                    </h3>
                    <h4 class="list-group-item-heading ">
                        Documents</h4>
                    <p class="list-group-item-text">
                        Where files are.</p>
                   </a><a href="/livwell-media" class="list-group-item visitor" style="background-color: #18bc9c;">
                        <h3 class="pull-right">
                            <i class="fa fa-globe"></i>
                        </h3>
                        <h4 class="list-group-item-heading ">
                            Media</h4>
                        <p class="list-group-item-text">
                            All eyes on us.</p>
                    </a>
            </div>

app/views/home/index.html.erb
<h1>home</h1>
   

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DreamProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <style type="text/css">
  	 .col-centered{
       margin: auto; max-width: 300px;
    }
  </style>
</head>
<body>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">FindWayToRun.com&nbsp;&nbsp;&nbsp;&nbsp;Admin Panal</a>
    </div>

    <div class="navbar-collapse collapse" id="bs-example-navbar-collapse-1" aria-expanded="false" style="height: 1px;">
      <ul class="nav navbar-nav">
       <% if user_signed_in? %>
        <li class="active"><a href="/dashboard">Dashboard </a></li>
     <!--    <li><a href="#">About Us</a></li>
         <li><a href="#">Address</a></li> -->
        <% end %>
        <!-- <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li> -->
      </ul>
     <!--  <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> -->
      <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
                  <li style="color: #b4bf1f;bottom: -21px;">Logged in as <%= current_user.email %>.</li>
                  <li><%= link_to 'Account', edit_user_registration_path, :class => 'btnsl ' %></li> |
                  <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'btnsl '  %></li>
                <% else %>
                  <li><%= link_to "Register New User ", new_user_registration_path, :class => 'btnsl '  %></li> |
                  <li><%= link_to "Log in", new_user_session_path, :class => 'btnsl '  %></li>
                <% end %>
      </ul>
    </div>
  </div>
</nav>
           

<br>
<div class="container">
	  		<%= yield %>
</div>
  	



</body>
</html>